### ISSUE TITLE
Missing mode set on init

### ISSUE THREAD

**Issue by ghost** [googolgl/go-pca9685#2]
I've been testing the lib on my raspberry and it seemed to work, but only if I had run at least one time another script that talks to the pca.
So I've had a look at this lib and it seems like the initial mode set is missing. Just add those:
```
Mode2 byte = 0x01	
AllCall byte = 0x01
INVRT byte = 0x10
OUTDRV byte = 0x04
pca.Conn.WriteRegU8(Mode2, OUTDRV)
pca.Conn.WriteRegU8(Mode1, AllCall)
time.Sleep(5*time.Millisecond)
```
lines of code to the init func. 
greets

**Comment by googolgl** [comment]
Thank you for issue.
I fixed trouble when first run.
But if you need change triggers in Mode1, Mode2 or other don`t rewrite value 
```
pca.Conn.WriteRegU8(Mode1, OUTDRV)
```

use next code:
```
oldMode, err := pca.Conn.ReadRegU8(Mode1)
pca.Conn.WriteRegU8(Mode1, oldMode|(new value) )
```
